# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json


###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token e69ce6c8ef87ab8dbe12df0272e2470435d2ced6

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token e69ce6c8ef87ab8dbe12df0272e2470435d2ced6

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator_id=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-03-27
Content-Type: application/json

###

DELETE  {{baseUrl}}/advertisements/12/
Content-Type: application/json
Authorization: Token 1b721395bcc3b80a3b0cdd546b1072caf15c5afc


