version: '3.9'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - web-app
  web-app:
    build: .
    ports:
      - "8555:6050"
    depends_on:
      - "postgre_db"
  postgre_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "new_db"
      POSTGRES_USER: "admin1"
      POSTGRES_PASSWORD: "adminpass"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", pg_isready -U admin -d new_db]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container_26_05
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "adminpass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

